#!/bin/bash
export FLASK_APP=mixmind_application.py
export UPLOADS_DEFAULT_DEST=stockdb
export FLASK_RUN_PORT=8888
if [[ $1 == 'prod' ]]; then
    export FLASK_ENV='production'
else
    export FLASK_ENV='development'
fi
flask run
